### PR TITLE
LUD06 Support w/ Wallet Picker

### PR DESCRIPTION
**Pull request by leesalminen**
Screen Shot 2022-12-27 at 4 00 51 PM

### CODE REVIEW

**Comment by leesalminen** [comment]
Are you open to PRs for this? Will continue working on this if so.

**Comment by monlovesmango** [comment]
yes definitely, this is awesome! can we put the ln wallet config on the settings page under profile?

**Comment by leesalminen** [comment]
> yes definitely, this is awesome! can we put the ln wallet config on the settings page under profile?

Yes definitely that’s already included on this branch too. I’ll clean it up tomorrow and formalize a PR

**Comment by leesalminen** [comment]
OK, I'm all ready for a code review on this.

**Comment by leesalminen** [comment]
Screen Shot 2022-12-29 at 10 20 40 PM
Screen Shot 2022-12-29 at 10 20 19 PM
Screen Shot 2022-12-29 at 10 19 59 PM
Screen Shot 2022-12-29 at 10 19 40 PM
Screen Shot 2022-12-29 at 10 27 11 PM

**Comment by monlovesmango** [comment]
this is so fucking cool. thank you thank you thank you.

do you think this is the last of the changes? I think i'm going to do a bit of refactoring when your through to make the BaseInvoice reusable for lightning payment/withdrawal requests

**Comment by leesalminen** [comment]
> this is so fucking cool. thank you thank you thank you.
> 
> do you think this is the last of the changes? I think i'm going to do a bit of refactoring when your through to make the BaseInvoice reusable for lightning payment/withdrawal requests

Almost done I think. Probably tomorrow and then I’ll turn it over to you!

**Comment by monlovesmango** [comment]
cool sounds good!

**Comment by leesalminen** [comment]
OK, I think I'm ready for you to refactor. If you want to take over, I've given you write access to my fork. Let me know if you want me to do anything. Hitting me up on nostr is probably fastest. I'm bitcoinjungle@no.str.cr or lee@no.str.cr.

**Comment by monlovesmango** [comment]
ok I pushed an update bc I got stuck and wanted to check with you on something. I want to allow users to type in ln address and then convert that to the lnurl for them. I was trying to use the lnurl-pay utils to do this. specifically the utils.parseLnUrl function but I can't seem to get it to return an lnurl for me. what am I doing wrong?

other than this my last todo is settings. want to allow people to turn off lightning tips, customize tip presets, and also want to store and remember the last used payment method and automatically open to that for the user on subsequent payment flows.

a couple things I wanted to ask about the wallet prefixes. first, I can't seem to get cash app to work on my phone. were you able to get it working? also how do you find prefixes for adding other wallets? was thinking of adding blue wallet and SBW but don't know how to check if this is possible for these wallets.

**Comment by monlovesmango** [comment]
updates to settings for lud06 is complete

only thing outstanding in my view is conversion of ln addresses into lnurl in settings. doesn't seem like lnurl-pay utils does this. do you know of an easy way to do this?

let me know your thoughts on my changes.

**Pull request merged**
