### PR TITLE
Support for PWA

### PR DESCRIPTION
**Pull request by diegogurpegui**
This PR allows astral to be built as a PWA for better UX in mobile.

My motivation was that I tried this on mobile and I wanted to improve the UX and have it as an app instead of a website.

I did the minimum changes to make this work, in order to be the less disruptive possible. However, many things can be improved or fixed, for example missing icons or better naming for the existing ones.

For the PWA mode to work, the build should be done accordingly:
```bash
$ quasar build -m pwa
```

A working example can be found in https://diegogurpegui.com/astral/ (open it from a mobile browser and try to _install_ it)

I'm not expert in Vue.js, much less in Quasar, so any suggestion or comment is appreciated.

### CODE REVIEW

**Comment by monlovesmango** [comment]
this is great, thank you!

I am not familiar with PWAs yet and was trying to test this locally but was unsuccessful. were you able to get the PWA working locally on mobile?

your version is working perfect for me. this would be an awesome feature for making astral more mobile friendly.

**Comment by diegogurpegui** [comment]
In order to make it work you just need to build it with this command as I stated before:
```bash
$ quasar build -m pwa
```
Once you do that the website ready to be run is located in `dist/pwa`. Just host the site from there and that's it.

Let me know if you have any trouble.

**Comment by monlovesmango** [comment]
so this part works for me. however when I open on mobile it doesn't have a little pop up asking to add it to the home screen (like on your site). when you tested it in this way you were able to add it to your home screen?

**Comment by diegogurpegui** [comment]
I tested it by publishing into my web. So the test is what you also tested it :)
I wanted it to be accessible via internet in order to do it, so I could open it from my mobile. I publish it using GitHub pages from my repo https://github.com/diegogurpegui/astral
But I did just that: build with "pwa" mode, and publish "dist/pwa" with GH pages.

**Comment by monlovesmango** [comment]
ok perfect thank you! something wrong on my end then. will merge once I can get this working in deployed docker container

**Comment by monlovesmango** [comment]
thanks again for this pr! this is a great feature and should have gotten around to it earlier (now that I know what pwa is.. haha). are you on nostr?

**Comment by diegogurpegui** [comment]
I'm glad it helps! Adding PWA was the first thing I wanted when I opened it on my mobile, hence the PR. If you want it, build it, right? :stuck_out_tongue: 

This is my pubkey in Nostr: `d1e60465c2b777325e9133f2100d2bb31416dca810f54a1d95665621c5dee193`

**Pull request merged**
